### ISSUE TITLE
Solving the mystery.

### ISSUE THREAD

**Issue by i404788** [vvvm23/vqvae-2#1]
Hey,

Thank you for creating this repository.

I was looking through the code, and just wanted to solve this mystery.
I think the reason you need `[0]` is because you are using the `*args` pattern in the parameters.

https://github.com/vvvm23/vqvae-2/blob/2576bde46d5f758b4f8dd2dba933f6b6d8e87ea0/datasets.py#L65-L68

**Comment by vvvm23** [comment]
Good catch!
I quite like the `*args` pattern so I kept it in, but I now unpack the dataset list before passing it to `LatentDataset.__init__`.
54ef491c8ee8fa493d3247319b6bdc46fade40bf

I'll likely redo this class in the future though, loading the entire dataset into memory at once is non-ideal.
