### ISSUE TITLE
How to generate contidion imgae？

### ISSUE THREAD

**Issue by yezichu** [vvvm23/vqvae-2#4]
I want to generate a picture of a specific class.

**Comment by vvvm23** [comment]
Hello!

Sorry, currently this repo only supports reconstructions. VQ-VAE-2 alone is not a generative model, and must be supported by some other generative model that makes the latents. I started making these (PixelSnail and GPT) but did not complete as my other responsibilities meant I didn't have time to work on this.

In the future, I will refactor the code in this repo, and add ways to generate images (as well as specific classes). But probably not until later this year.

If you want to do yourself, you can train a VQ-VAE-2 model using this repo, then extract latents for your dataset that has class data. Then you can train a model like PixelSnail or GPT on these latents and the class information.

Sorry, I can't be of help right now ~
